apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: securesign-pipelines-demo
resources:
  - github-push-triggerbinding.yaml
  - gregory-pereira-gpg-pub.yaml
  - namespace.yaml 
  - sigstore-triggerbinding.yaml
