apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: securesign-pipelines-demo
resources:
  - gregory-pereira-gpg-pub.yaml
  - verify-commit-signature-task.yaml
  - verify-source-code-pipeline.yaml
  - triggers-and-listeners
