apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-sign-pipeline
spec:
  params: 
    - name: REPO_HOST
      type: string
    - name: COMMIT_SHA
      type: string
    - name: TLSVERIFY
      type: string
    - name: BUILD_EXTRA_ARGS
      type: string
    - name: IMAGE_REPO
      type: string
    - name: IMAGE_TAG
      type: string
    - name: GIT_REF
      type: string
    - name: COMMIT_DATE
      type: string
    - name: COMMIT_AUTHOR_EMAIL
      type: string
    - name: COMMIT_MESSAGE
      type: string
    - name: GIT_REPO
      type: string
  tasks: 
    - name: pull-source-code 
      params:
        - name: url 
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REF)
        - name: deleteExisting
          value: 'true'
      taskRef: 
        kind: ClusterTask
        name: git-clone
      workspaces: 
        - name: output
          workspace: shared-data
    - name: verify-commit-signature
      runAfter:
        - pull-source-code 
      params:
      taskRef:
        kind: Task
        name: verify-commit-signature-task
      workspaces: 
        - name: repository
          workspace: shared-data
        - name: secrets
          workspace: secrets
    - name: build-sign-image
      params:
        - name: TLSVERIFY
          value: $(params.TLSVERIFY)
        - name: BUILD_EXTRA_ARGS
          value: >-
            --label=io.openshift.build.commit.author='$(params.COMMIT_AUTHOR_EMAIL)'
            --label=io.openshift.build.commit.date='$(params.COMMIT_DATE)'
            --label=io.openshift.build.commit.id='$(params.COMMIT_SHA)'
            --label=io.openshift.build.commit.message='$(params.COMMIT_MESSAGE)'
            --label=io.openshift.build.commit.ref='$(params.GIT_REF)'
            --ulimit=nofile=4096:4096
        - name: IMAGE
          value: '$(params.IMAGE_REPO):$(params.IMAGE_TAG)'
      retries: 1
      runAfter:
        - verify-commit-signature
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-data
  workspaces:
    - name: secrets 
    - name: shared-data
